ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}
#
ARG PUID=1000
ARG PGID=1000
#
ENV GRAFANA_HOME=/var/lib/grafana
#
RUN set -ex && \
    addgroup -g ${PGID} -S grafana && \
    adduser -u ${PUID} -G grafana -h ${GRAFANA_HOME} -D grafana
    echo 'hosts: files dns' >> /etc/nsswitch.conf && \
    apk add -Uu --no-cache ca-certificates curl openssl fontconfig \
    && VERSION=$(curl -SL https://api.github.com/repos/grafana/grafana/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]' | sed -e 's_v__') \
    && echo "Using version: $VERSION" && \
    && curl -o /tmp/grafana-${VERSION}.linux-x64.tar.gz -SL https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-${VERSION}.linux-x64.tar.gz \
    && cd /tmp/ \
    && tar -xzf grafana-${VERSION}.linux-x64.tar.gz \
    && mv grafana-${VERSION}/* ${GRAFANA_HOME}/ \
    && mv ${GRAFANA_HOME}/bin/* /usr/local/bin/ \
    && mkdir -p ${GRAFANA_HOME}/{dashboards,data,logs,plugins,provisioning} \
# && mkdir ${GRAFANA_HOME}/ \
# && ln -s /grafana/plugins ${GRAFANA_HOME}/plugins \
# && grafana-cli plugins update-all \
# && rm -f ${GRAFANA_HOME}/conf/*.ini \
    && chown -R grafana:grafana ${GRAFANA_HOME} \
    && rm -rf /var/cache/apk/* /tmp/*
#
COPY root/ /
#
VOLUME  ["/var/lib/grafana/transport"]
#
EXPOSE 3000
#
ENTRYPOINT ["/init"]
