#!/usr/bin/with-contenv bash
set -e

[[ -f ${GRAFANA_HOME}/conf/defaults.ini ]] \
    && echo 'Found defaults.ini' \
    || ( mkdir -p ${GRAFANA_HOME}/conf && cp /defaults/defaults.ini ${GRAFANA_HOME}/conf/defaults.ini );

if [ ! -z ${GF_AWS_PROFILES+x} ]; then
    mkdir -p ${GRAFANA_HOME}/.aws/
    touch ${GRAFANA_HOME}/.aws/credentials

    for profile in ${GF_AWS_PROFILES}; do
        access_key_varname="GF_AWS_${profile}_ACCESS_KEY_ID"
        secret_key_varname="GF_AWS_${profile}_SECRET_ACCESS_KEY"
        region_varname="GF_AWS_${profile}_REGION"

        if [ ! -z "${!access_key_varname}" -a ! -z "${!secret_key_varname}" ]; then
            echo "[${profile}]" >> ${GRAFANA_HOME}/.aws/credentials
            echo "aws_access_key_id = ${!access_key_varname}" >> ${GRAFANA_HOME}/.aws/credentials
            echo "aws_secret_access_key = ${!secret_key_varname}" >> ${GRAFANA_HOME}/.aws/credentials
            if [ ! -z "${!region_varname}" ]; then
                echo "region = ${!region_varname}" >> ${GRAFANA_HOME}/.aws/credentials
            fi
        fi
    done

    chown grafana:grafana -R ${GRAFANA_HOME}
    chown grafana:grafana -R ${GRAFANA_HOME}/.aws
    chmod 600 ${GRAFANA_HOME}/.aws/credentials
fi

if [ ! -z ${GF_INSTALL_PLUGINS} ]; then
  OLDIFS=$IFS
  IFS=','
  for plugin in ${GF_INSTALL_PLUGINS}; do
    s6-setuidgid grafana exec grafana-cli plugins install ${plugin}
  done
  IFS=$OLDIFS
fi

s6-setuidgid grafana exec grafana-cli plugins update-all
